name: Next.js CI

on: [push]

env:
  NEXT_PUBLIC_ALGOLIA_ARTICLES_INDEX_NAME: production_jbb_articles
  NEXT_PUBLIC_ALGOLIA_APP_ID: ${{ secrets.NEXT_PUBLIC_ALGOLIA_APP_ID }}
  NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY: ${{ secrets.NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY }}
  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
  NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
  NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
  NEXT_PUBLIC_API_TOKEN: ${{ secrets.NEXT_PUBLIC_API_TOKEN }}
  NEXT_PUBLIC_GOOGLE_ANALYTICS: ${{ secrets.NEXT_PUBLIC_GOOGLE_ANALYTICS }}

jobs:
  install-cache:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["22.22.x"]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache yarn dependencies
        uses: actions/cache@v4
        id: cache-dependencies
        with:
          path: node_modules
          key: yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-${{ runner.os }}-
      - name: Install dependencies
        if: ${{ steps.cache-dependencies.outputs.cache-hit != 'true' }}
        run: yarn --frozen--lockfile

  type-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["22.22.x"]
    needs: install-cache
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Restore yarn dependencies
        uses: actions/cache@v4
        id: cache-dependencies
        with:
          path: node_modules
          key: yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-${{ runner.os }}-
      - name: Check types
        run: |
          yarn type-check
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["22.22.x"]
    needs: install-cache
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Restore yarn dependencies
        uses: actions/cache@v4
        id: cache-dependencies
        with:
          path: node_modules
          key: yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-${{ runner.os }}-
      - name: Run lint
        run: |
          yarn lint
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["22.22.x"]
    needs: install-cache
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Restore yarn dependencies
        uses: actions/cache@v4
        id: cache-dependencies
        with:
          path: node_modules
          key: yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-${{ runner.os }}-
      - name: Run test
        run: |
          yarn test

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["22.22.x"]
    needs: [type-check, lint, unit-test]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Restore yarn dependencies
        uses: actions/cache@v4
        id: cache-dependencies
        with:
          path: node_modules
          key: yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-${{ runner.os }}-
      - name: Run build
        run: |
          yarn build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: .next
          include-hidden-files: true
          if-no-files-found: error
          retention-days: 1

  e2e-tests-chrome:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: ["22.22.x"]
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - name: Restore yarn dependencies
        uses: actions/cache@v4
        id: cache-dependencies
        with:
          path: node_modules
          key: yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-${{ runner.os }}-
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: .next
      - name: Run cypress
        uses: cypress-io/github-action@v6
        with:
          install: true
          start: yarn start
          browser: chrome
